# Generated by Django 2.2.2 on 2020-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtticket',
            name='ticket',
        ),
    ]
