# Generated by Django 2.2.2 on 2020-09-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=360)),
                ('icon', models.ImageField(upload_to='carrier_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrive_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrive_date', models.DateField()),
                ('price', models.FloatField(default=0)),
                ('currency_name', models.CharField(default='USD', max_length=3)),
                ('arrive_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_tickets', to='tick_ticket.City')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tick_ticket.Carrier')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_tickets', to='tick_ticket.City')),
            ],
        ),
    ]
