# Generated by Django 2.2.2 on 2020-09-21 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0003_auto_20200921_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available_until',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrive_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
