# Generated by Django 2.2.2 on 2020-10-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0003_boughtticket_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoughtTicket',
        ),
    ]
