# Generated by Django 2.2.2 on 2020-10-04 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0004_delete_boughtticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_on', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_information', to='tick_ticket.Ticket')),
            ],
        ),
    ]
