# Generated by Django 2.2.2 on 2020-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0005_boughtticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number_of_available',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
