# Generated by Django 2.2.2 on 2020-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0008_auto_20200922_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=15, max_digits=16, null=True)),
                ('name_on_card', models.CharField(max_length=60, null=True)),
                ('expire_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_cards',
            field=models.ManyToManyField(related_name='owner', to='tick_ticket.CreditCard'),
        ),
    ]
