# Generated by Django 2.2.2 on 2020-10-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0011_auto_20201019_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transport_name',
            field=models.CharField(blank=True, default='any', max_length=20),
        ),
    ]
