# Generated by Django 2.2.2 on 2020-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0014_auto_20201002_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_perm',
            field=models.BooleanField(default=False),
        ),
    ]
