# Generated by Django 2.2.2 on 2020-10-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tick_ticket', '0015_user_has_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_perm',
        ),
    ]
